### ISSUE TITLE
Enhancement - Annotation plugin support

### ISSUE THREAD

**Issue by stephanstapel** [mattosaurus/ChartJSCore#103]
I'm currently working on support for the annotation plugin:
https://www.chartjs.org/chartjs-plugin-annotation/latest/guide/

@mattosaurus : would it be ok for you to integrate this into ChartJSCore? And if so, could we integrate this as dedicated plugin classes as a property of the Plugins class?

**Comment by mattosaurus** [comment]
Hi, yeah I'm happy for this to be added to the plugins class. I'll take a look at this when I get a chance but feel free to sumbit a PR as well if necessary.

**Comment by thalter** [comment]
@stephanstapel  - This feature is semi-broken. I observed the following Issues:

1. Optional values should be nullable (e.g. double?, bool?, etc.), so that they don't get generated in the rendered JSON if not specified. Most of the optional numeric values currently have a default value of zero, which causes strange behaviors on the charts (e.g. if you want a horizontal line, yMin and yMax should not be rendered). 
2. Most of your numeric values are decimal. By convention, numeric values elsewhere in the ChartJSCore code are double (or double? for optional values)
3. xScaleID and yScaleID should be strings, and not numeric values.

**Comment by stephanstapel** [comment]
@thalter : thanks for letting me know. I'll look into this and issue a PR!

**Comment by stephanstapel** [comment]
@thalter : would you remove the default value setting like here:

![grafik](https://github.com/user-attachments/assets/d0ab4345-8113-4a1b-8d07-eae1891a9138)

and make this 

```public double? z { get; set: }```

?

**Comment by thalter** [comment]
Yep, you got it. Obviously don't set default values for nullable types, as that defeats the purpose of making them nullable. 😉

**Comment by stephanstapel** [comment]
> Yep, you got it. Obviously don't set default values for nullable types, as that defeats the purpose of making them nullable. 😉

obviously. That's wasn't really my question but rather if you'd set default values for properties.
Happy to remove those, then make all those properties nullable. PR on the way.

**Comment by stephanstapel** [comment]
btw, here it is:
https://github.com/mattosaurus/ChartJSCore/pull/106

**Comment by mattosaurus** [comment]
Good work @stephanstapel and @thalter. Thanks for creating this PR.

I've created a new release and published to NuGet now.
