### ISSUE TITLE
LineDataset Properties

### ISSUE THREAD

**Issue by 46692** [mattosaurus/ChartJSCore#13]
The 'Fill' and 'SteppedLine' properties of a LineDataset should be string instead of bool? to allow values such as 'end', '+2' etc.
These pages offer some examples of what I mean:
http://www.chartjs.org/samples/latest/charts/area/line-datasets.html
http://www.chartjs.org/samples/latest/charts/line/stepped.html

**Comment by mattosaurus** [comment]
Hi @Oelkrug, It looks like these fields can be either bool, int or string.
https://github.com/chartjs/Chart.js/blob/master/docs/charts/area.md
I've updated the code to accept a string input and if the value of the field is a boolean or integer than that will be output (without quotes), otherwise a standard quoted string will be output.

These changes have been published in v1.2.2 of the package.
