### ISSUE TITLE
Convert to javascript

### ISSUE THREAD

**Issue by psclkhoury** [mattosaurus/ChartJSCore#45]
Hey, I was wondering what is the easiest way to convert a Chart object to javascript code (a string).

What I'm trying to do is construct a chart in c# then send it to puppeteer to generate a report. So I need to convert the chart object to a string so I can inject it in a script tag.

The CreateChartCode returns a Json string so it's not exactly what I want.

Thanks

**Comment by mattosaurus** [comment]
This library works by serializing the C# Chart object to JSON as that's essentially what the chart.js javascript is, the SerializeBody method on the Chart object will give you the chart structure without the canvas creation so that might be what you need. If not send me an example of the string you're trying to achieve and I'll see if I can help.
